# Generated by Django 5.0.6 on 2024-10-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0002_rename_ecrypted_password_customuser_encrypted_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_id', models.CharField(max_length=50)),
                ('cocktail_name', models.CharField(max_length=500)),
                ('cocktail_image_url', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktailapp.customuser')),
            ],
        ),
    ]
